# Generated by Django 4.2.7 on 2023-11-27 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_experience_short_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='short_description',
            field=models.TextField(),
        ),
    ]
