# Generated by Django 4.2.7 on 2023-11-27 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_experience_short_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='short_description',
        ),
        migrations.AddField(
            model_name='project',
            name='short_description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
