# Generated by Django 4.2.7 on 2023-11-27 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_experience_short_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='company',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
