# Generated by Django 4.2.7 on 2023-12-04 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_project_options_alter_project_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='experience',
            options={'ordering': ['-start_date', '-end_date']},
        ),
    ]
